export const NAV_SHOP = 'NAV_SHOP';
export const NAV_READ = 'NAV_READ';
export const NAV_VISIT = 'NAV_VISIT';
export const NAV_SEARCH = 'NAV_SEARCH';
export const NAV_LOGIN = 'NAV_LOGIN';
export const NAV_CART = 'NAV_CART';
export const NAV_LOGO = 'NAV_LOGO';
export const NAV_SHOP_1 = 'NAV_SHOP_1';
export const NAV_SHOP_2 = 'NAV_SHOP_2';
export const NAV_SHOP_PRODUCT_RADIO = 'NAV_SHOP_PRODUCT_RADIO';
export const NAV_SHOP_PRODUCT_CTA = 'NAV_SHOP_PRODUCT_CTA';
export const NAV_VISIT_INPUT = 'NAV_VISIT_INPUT';
export const NAV_VISIT_CHECKBOX = 'NAV_VISIT_CHECKBOX';

export const FOOTER_LINK = 'FOOTER_LINK';

export const ADD_TO_CART_LARGE_CTA = 'ADD_TO_CART_LARGE_CTA';
export const ADD_TO_CART_SMALL_CTA = 'ADD_TO_CART_SMALL_CTA';
export const ADD_TO_CART_TEST = 'ADD_TO_CART_TEST';

export const CART_CHECKOUT_CTA = 'CART_CHECKOUT_CTA';
export const CART_PROMO_CTA = 'CART_PROMO_CTA';
export const CART_PROMO_INPUT = 'CART_PROMO_INPUT';
export const CART_PROMO_AMOUNT = 'CART_PROMO_AMOUNT';
export const CART_HEADING = 'CART_HEADING';
export const CART_CLOSE = 'CART_CLOSE';

export const CHECKOUT_CUSTOMER_EMAIL = 'CHECKOUT_CUSTOMER_EMAIL';
export const CHECKOUT_CUSTOMER_PASSWORD = 'CHECKOUT_CUSTOMER_PASSWORD';
export const CHECKOUT_CUSTOMER_PREFIX = 'CHECKOUT_CUSTOMER_PREFIX';
export const CHECKOUT_CUSTOMER_FIRST_NAME = 'CHECKOUT_CUSTOMER_FIRST_NAME';
export const CHECKOUT_CUSTOMER_LAST_NAME = 'CHECKOUT_CUSTOMER_LAST_NAME';
export const CHECKOUT_CUSTOMER_SUBMIT = 'CHECKOUT_CUSTOMER_SUBMIT';
export const CHECKOUT_CUSTOMER_GUEST_BUTTON = 'CHECKOUT_CUSTOMER_GUEST_BUTTON';
export const ADDRESS_COUNTRY = 'ADDRESS_COUNTRY';
export const ADDRESS_LINE_1 = 'ADDRESS_LINE_1';
export const ADDRESS_LINE_2 = 'ADDRESS_LINE_2';
export const ADDRESS_COMPANY = 'ADDRESS_COMPANY';
export const ADDRESS_REGION = 'ADDRESS_REGION';
export const ADDRESS_TOWN = 'ADDRESS_TOWN';
export const ADDRESS_POSTAL_CODE = 'ADDRESS_POSTAL_CODE';
export const ADDRESS_COUNTRY_CODE = 'ADDRESS_COUNTRY_CODE';
export const ADDRESS_PHONE_NUMBER = 'ADDRESS_PHONE_NUMBER';
export const CHECKOUT_SHIPPING_METHOD = 'CHECKOUT_SHIPPING_METHOD';
export const CHECKOUT_GIFT = 'CHECKOUT_GIFT';
export const CHECKOUT_GIFT_MESSAGE_CHECKBOX = 'CHECKOUT_GIFT_MESSAGE_CHECKBOX';
export const CHECKOUT_GIFT_MESSAGE = 'CHECKOUT_GIFT_MESSAGE';
export const CHECKOUT_GIFT_INSTRUCTIONS_CHECKBOX =
  'CHECKOUT_GIFT_INSTRUCTIONS_CHECKBOX';
export const CHECKOUT_GIFT_INSTRUCTIONS = 'CHECKOUT_GIFT_INSTRUCTIONS';
export const CHECKOUT_SHIPPING_SUBMIT = 'CHECKOUT_SHIPPING_SUBMIT';
export const CHECKOUT_PAYMENT_METHOD = 'CHECKOUT_PAYMENT_METHOD';
export const CHECKOUT_PAYMENT_CARD_HOLDER = 'CHECKOUT_PAYMENT_CARD_HOLDER';
export const CHECKOUT_PAYMENT_CARD = 'CHECKOUT_PAYMENT_CARD';
export const CHECKOUT_PAYMENT_EXPIRATION = 'CHECKOUT_PAYMENT_EXPIRATION';
export const CHECKOUT_PAYMENT_CVC = 'CHECKOUT_PAYMENT_CVC';
export const CHECKOUT_PAYMENT_GIFTCARD_CODE = 'CHECKOUT_PAYMENT_GIFTCARD_CODE';
export const CHECKOUT_PAYMENT_GIFTCARD_PIN = 'CHECKOUT_PAYMENT_GIFTCARD_PIN';
export const CHECKOUT_BILLING_SAME_SHIPPING = 'CHECKOUT_BILLING_SAME_SHIPPING';
export const CHECKOUT_BILLING_TAX = 'CHECKOUT_BILLING_TAX';
export const CHECKOUT_PAYMENT_SUBMIT = 'CHECKOUT_PAYMENT_SUBMIT';
export const CHECKOUT_SAMPLES_RADIO = 'CHECKOUT_SAMPLES_RADIO';
export const CHECKOUT_SAMPLES_SUBMIT = 'CHECKOUT_SAMPLES_SUBMIT';
export const CHECKOUT_REVIEW_TOTAL = 'CHECKOUT_REVIEW_TOTAL';
export const CHECKOUT_REVIEW_TOS_CHECKBOX = 'CHECKOUT_REVIEW_TOS_CHECKBOX';
export const CHECKOUT_REVIEW_SUBMIT = 'CHECKOUT_REVIEW_SUBMIT';

export const CONFIRMATION_ACCOUNT_BUTTON = 'CONFIRMATION_ACCOUNT_BUTTON';

export const LOAD_MORE_BUTTON = 'LOAD_MORE_BUTTON';
