export default {
  initialZoom: 14,
  center: { lat: -37.8064, lng: 144.9826 },
  customPinMarker: { lat: -37.78863, lng: 144.9847727, type: 'PIN' },
  customPinMarkerCenter: { lat: -37.78863, lng: 144.9847727 },
  copy: {
    storeLocator: {
      label: 'Store locator',
      message: 'Visit our nearby stores.',
      title: 'Open store locator link',
      url: '/',
    },
    directions: 'Directions to',
    openingHours: {
      alternateHoursNote: 'Special opening hours',
      heading: 'Opening hours',
    },
  },
  customPlaceMarker: {
    id: 'aesop-collins-street',
    lat: -37.813971,
    lng: 144.970604,
    storeName: 'Aesop Collins Street',
    storeType: 'SIGNATURE_STORE',
    type: 'PLACE',
    address: '87 Collins Street, Melbourne 3000',
    phoneNumber: '+61 3 9650 3027',
    openingHours: [
      { dayName: 'Monday', hours: '11am - 4pm', id: '1' },
      { dayName: 'Tuesday', hours: '10am - 3pm', id: '2', isAlternate: true },
      { dayName: 'Wednesday', hours: '10am - 3pm', id: '3' },
      { dayName: 'Thursday', hours: '10am - 3pm', id: '4' },
      { dayName: 'Friday', hours: '10am - 3pm', id: '5' },
      { dayName: 'Saturday', hours: '10am - 3pm', id: '6', isAlternate: true },
      { dayName: 'Sunday', hours: '10am - 3pm', id: '7' },
    ],
  },
  customPlaceMarkerCenter: {
    lat: -37.813971,
    lng: 144.970604,
  },
  places: [
    {
      id: 'aesop-fitzroy',
      lat: -37.8064,
      lng: 144.9826,
      storeName: 'Aesop Fitzroy',
      storeType: 'SIGNATURE_STORE',
      address: '242 Gertrude Street, Fitzroy VIC 3065',
      phoneNumber: '+61 3 9419 8356',
      openingHours: [
        { dayName: 'Monday', hours: '11am - 4pm', id: '1' },
        { dayName: 'Tuesday', hours: '10am - 3pm', id: '2', isAlternate: true },
        { dayName: 'Wednesday', hours: '10am - 3pm', id: '3' },
        { dayName: 'Thursday', hours: '10am - 3pm', id: '4' },
        { dayName: 'Friday', hours: '10am - 3pm', id: '5' },
        {
          dayName: 'Saturday',
          hours: '10am - 3pm',
          id: '6',
          isAlternate: true,
        },
        { dayName: 'Sunday', hours: '10am - 3pm', id: '7' },
      ],
    },
    {
      id: 'aesop-qv',
      lat: -37.810711,
      lng: 144.965485,
      storeName: 'Aesop QV',
      storeType: 'SIGNATURE_STORE',
      openingHours: [
        { dayName: 'Monday', hours: '11am - 4pm', id: '1' },
        { dayName: 'Tuesday', hours: '10am - 3pm', id: '2', isAlternate: true },
        { dayName: 'Wednesday', hours: '10am - 3pm', id: '3' },
        { dayName: 'Thursday', hours: '10am - 3pm', id: '4' },
        { dayName: 'Friday', hours: '10am - 3pm', id: '5' },
        {
          dayName: 'Saturday',
          hours: '10am - 3pm',
          id: '6',
          isAlternate: true,
        },
        { dayName: 'Sunday', hours: '10am - 3pm', id: '7' },
      ],
    },
    {
      id: 'aesop-south-yarra',
      lat: -37.8388125,
      lng: 144.9914976,
      storeName: 'Aesop South Yarra',
      storeType: 'SIGNATURE_STORE',
      openingHours: [
        { dayName: 'Monday', hours: '11am - 4pm', id: '1' },
        { dayName: 'Tuesday', hours: '10am - 3pm', id: '2', isAlternate: true },
        { dayName: 'Wednesday', hours: '10am - 3pm', id: '3' },
        { dayName: 'Thursday', hours: '10am - 3pm', id: '4' },
        { dayName: 'Friday', hours: '10am - 3pm', id: '5' },
        {
          dayName: 'Saturday',
          hours: '10am - 3pm',
          id: '6',
          isAlternate: true,
        },
        { dayName: 'Sunday', hours: '10am - 3pm', id: '7' },
      ],
    },
    {
      id: 'myer-melbourne',
      lat: -37.813791,
      lng: 144.964008,
      storeName: 'Myer Melbourne',
      storeType: 'DEPARTMENT_STORE',
      openingHours: [
        { dayName: 'Monday', hours: '11am - 4pm', id: '1' },
        { dayName: 'Tuesday', hours: '10am - 3pm', id: '2', isAlternate: true },
        { dayName: 'Wednesday', hours: '10am - 3pm', id: '3' },
        { dayName: 'Thursday', hours: '10am - 3pm', id: '4' },
        { dayName: 'Friday', hours: '10am - 3pm', id: '5' },
        {
          dayName: 'Saturday',
          hours: '10am - 3pm',
          id: '6',
          isAlternate: true,
        },
        { dayName: 'Sunday', hours: '10am - 3pm', id: '7' },
      ],
    },
    {
      id: 'aesop-newtown',
      lat: -33.893405,
      lng: 151.18367,
      storeName: 'Aesop Newtown',
      storeType: 'SIGNATURE_STORE',
      address: '134A King Street, Newtown, NSW 2042',
      phoneNumber: '+61 2 9517 3319',
      openingHours: [
        { dayName: 'Monday', hours: '11am - 4pm', id: '1' },
        { dayName: 'Tuesday', hours: '10am - 3pm', id: '2', isAlternate: true },
        { dayName: 'Wednesday', hours: '10am - 3pm', id: '3' },
        { dayName: 'Thursday', hours: '10am - 3pm', id: '4' },
        { dayName: 'Friday', hours: '10am - 3pm', id: '5' },
        {
          dayName: 'Saturday',
          hours: '10am - 3pm',
          id: '6',
          isAlternate: true,
        },
        { dayName: 'Sunday', hours: '10am - 3pm', id: '7' },
      ],
    },
  ],
};
